language: node_js

env:
  -npm start
    - node index.js
     - DB=postgresql://postgres@localhost:5432/shoe_api_test
node_js:
        - "8.9.4"
        #   script:
#     -npm start index.js

before_script:
  - psql -c 'create database  shoe_api_test;' -U postgres
  - psql -U postgres -d shoe_api_test -a -f sql_scripts/shoe_api_tables.sql

# install:
#   - npm install
 


addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
